# Generated by Django 6.0.1 on 2026-01-25 08:45

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashyboard', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Basic'), ('2', 'Reverse'), ('3', 'Basic and Reverse '), ('4', 'Type in Answer')], default='1', max_length=2)),
                ('front', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(3)])),
                ('back', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(3)])),
                ('source', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashyboard.decks')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
