# Generated by Django 6.0.1 on 2026-01-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashyboard', '0002_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='source',
            new_name='detailed_info',
        ),
    ]
